language: node_js
node_js:
  - "0.10"
  - "0.8"
  - "0.11"
before_install:
  - "npm install -g mocha"
  - "npm install blanket"
  - "npm install coveralls mocha-lcov-reporter"
before_script:
  - "make init"
after_success:
  - "make coveralls-spin"
